### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by mithi** [gauravmm/Hexapod-IK#1]
Thanks for sharing your project, I'm using it as a reference for my own
hexapod simulator..
https://github.com/mithi/hexapod-robot-simulator

I just noticed that the link in your repo is broken, 
you might want to fix that broken link
https://www.gauravmanek.com/blog/2015/hexapod-step-planner/

Thanks again!

**Comment by gauravmm** [comment]
Thank you for letting me know! I'll fix the link.
